name: telco-churn-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - mlflow
      - matplotlib
      - seaborn
