name: CI - MLflow Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run MLflow Project (No Conda)
      - name: Run MLflow Project
        run: |
          mlflow run MLProject --no-conda

      # 5. Upload trained model artifact
      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: mlruns/**/artifacts/**

      # 6. Upload mlruns folder (tracking data)
      - name: Upload mlruns folder
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

  # (Opsional) Job kedua buat restore artifacts
  validate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: ./restored-model

      - name: Download mlruns folder
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: ./restored-mlruns

      - name: List restored files
        run: ls -R ./restored-model ./restored-mlruns
