name: CI MLflow Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Run MLflow project
      run: mlflow run MLProject --env-manager=local

    - name: Upload trained model artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: mlruns/**/artifacts/**

    - name: Upload mlruns folder
      uses: actions/upload-artifact@v3
      with:
        name: mlruns
        path: mlruns/
